### ISSUE TITLE
Couldn't end the meet successfully

### ISSUE THREAD

**Issue by reeswar21** [SHUR1K-N/MeetNinja-Google-Meet-Bot#13]
hey..can you check this out?
```
Navigating to Google Meet #1...[32m Success![0m
Entering Google Meet #1...[32m Success![0m
[32mNow attending Google Meet #1 @09:19:22[0mTraceback (most recent call last):
  File "/Users/reeswar/Dropbox/My Mac (Reeswars-MacBook-Pro.local)/Downloads/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 242, in <module>
    endMeet()
  File "/Users/reeswar/Dropbox/My Mac (Reeswars-MacBook-Pro.local)/Downloads/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 177, in endMeet
    endButton.click()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=87.0.4280.67)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reeswar/Dropbox/My Mac (Reeswars-MacBook-Pro.local)/Downloads/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 259, in <module>
    print(e)
NameError: name 'e' is not defined
>>> 
```

**Comment by SHUR1K-N** [comment]
You may have minimized the Google Chrome window. You may keep the window maximized and open in the background, but explicitly "minimizing" the window will not let MeetNinja work on it. You may read about this in the [Notes section](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot#note) of the MeetNinja page.
