### ISSUE TITLE
"TypeError: __init__() got an unexpected keyword argument 'service'" [SOLVED]

### ISSUE THREAD

**Issue by denppa** [SHUR1K-N/MeetNinja-Google-Meet-Bot#18]
Hey kind dev!

I use 64bit Arch linux and latest firefox 85.0. And this error popped up. Any idea how to fix it?
Know naught about why the error `service` popped up. Read previous issues, could not fix it myself sorry.

```$  python MeetNinja.py 

   ███▄ ▄███▓▓█████ ▓█████▄▄▄█████▓ ███▄    █  ██▓ ███▄    █  ▄▄▄██▀▀▀▄▄▄
  ▓██▒▀█▀ ██▒▓█   ▀ ▓█   ▀▓  ██▒ ▓▒ ██ ▀█   █ ▓██▒ ██ ▀█   █    ▒██  ▒████▄
  ▓██    ▓██░▒███   ▒███  ▒ ▓██░ ▒░▓██  ▀█ ██▒▒██▒▓██  ▀█ ██▒   ░██  ▒██  ▀█▄
  ▒██    ▒██ ▒▓█  ▄ ▒▓█  ▄░ ▓██▓ ░ ▓██▒  ▐▌██▒░██░▓██▒  ▐▌██▒▓██▄██▓ ░██▄▄▄▄██
  ▒██▒   ░██▒░▒████▒░▒████▒ ▒██▒ ░ ▒██░   ▓██░░██░▒██░   ▓██░ ▓███▒   ▓█   ▓██▒
  ░ ▒░   ░  ░░░ ▒░ ░░░ ▒░ ░ ▒ ░░   ░ ▒░   ▒ ▒ ░▓  ░ ▒░   ▒ ▒  ▒▓▒▒░   ▒▒   ▓▒█░
  ░  ░      ░ ░ ░  ░ ░ ░  ░   ░    ░ ░░   ░ ▒░ ▒ ░░ ░░   ░ ▒░ ▒ ░▒░    ▒   ▒▒ ░
  ░      ░      ░      ░    ░         ░   ░ ░  ▒ ░   ░   ░ ░  ░ ░ ░    ░   ▒
         ░      ░  ░   ░  ░                 ░  ░           ░  ░   ░        ░  ░
                    ------------------------------------
                    || MeetNinja: The Google Meet Bot ||
                    ------------------------------------

Checking for MeetNinja updates... You are using the latest version!


Initializing browser...Traceback (most recent call last):
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 247, in <module>
    driver = initBrowser()
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 141, in initBrowser
    driver = webdriver.Firefox(service=serv, options=firefoxOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 279, in <module>
    print(e)
NameError: name 'e' is not defined
```

**Comment by SHUR1K-N** [comment]
Hey! This has an [existing closed Issue](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/17); you may follow its thread to check if the instructions fix it for you.

Edit: You already mentioned you read previous Issue. Apologies, have you read the specific linked Issue as well?

**Comment by denppa** [comment]
> Hey! This has an [existing closed Issue](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/17); you may follow its thread to check if the instructions fix it for you.
> 
> Edit: You already mentioned you read previous Issue. Apologies, have you read the specific linked Issue as well?

Hello Dev!

Yes, the previous person had a different scenario. He was using a ESR browser and failed to install another one, which is knowledge shortage on his side. But I already updated my browser to be the latest version 85.0 Firefox. I would like to think that this might be something you can fix on the code basis.

**Comment by SHUR1K-N** [comment]
Correct. Also, you are fine with the Firefox version you have (that's what my test machines have as well). The issue is, MeetNinja is running just fine with every Linux machine I have tested it on; had another round of testing just as I saw this Issue! I will leave this Issue open for now and do some research as to what the culprit could be and then revert back.

**Comment by denppa** [comment]
The firefox I used is normal for everything. I think it might be the Arch Linux OS that you didn't account for?

Googling this python error seems to pop up many results, sadly though I don't know how to code, so it will be a lot slower for me to work on that aspect, but I will try.

If you do need more error logs/ report, let me know how and I will try to get it to you!

**Comment by SHUR1K-N** [comment]
Arch Linux should not be an issue as far as I can think, because the previous user's issue was similar; even though they had a problem installing the non-ESR Firefox, the error should not be displayed in the first place whatsoever.

Correct, Google shows the same traceback, but for different elements which do not make much sense to this problem as every individual element has its own culprit. I do not think there are any more logs/reports you can help with, this is sufficient enough, thank you!

**Comment by denppa** [comment]
Yup! I did try both browsers but it did not work, but forgot to post the traceback for Chrome, just in case:
```
$  python MeetNinja.py 

   ███▄ ▄███▓▓█████ ▓█████▄▄▄█████▓ ███▄    █  ██▓ ███▄    █  ▄▄▄██▀▀▀▄▄▄
  ▓██▒▀█▀ ██▒▓█   ▀ ▓█   ▀▓  ██▒ ▓▒ ██ ▀█   █ ▓██▒ ██ ▀█   █    ▒██  ▒████▄
  ▓██    ▓██░▒███   ▒███  ▒ ▓██░ ▒░▓██  ▀█ ██▒▒██▒▓██  ▀█ ██▒   ░██  ▒██  ▀█▄
  ▒██    ▒██ ▒▓█  ▄ ▒▓█  ▄░ ▓██▓ ░ ▓██▒  ▐▌██▒░██░▓██▒  ▐▌██▒▓██▄██▓ ░██▄▄▄▄██
  ▒██▒   ░██▒░▒████▒░▒████▒ ▒██▒ ░ ▒██░   ▓██░░██░▒██░   ▓██░ ▓███▒   ▓█   ▓██▒
  ░ ▒░   ░  ░░░ ▒░ ░░░ ▒░ ░ ▒ ░░   ░ ▒░   ▒ ▒ ░▓  ░ ▒░   ▒ ▒  ▒▓▒▒░   ▒▒   ▓▒█░
  ░  ░      ░ ░ ░  ░ ░ ░  ░   ░    ░ ░░   ░ ▒░ ▒ ░░ ░░   ░ ▒░ ▒ ░▒░    ▒   ▒▒ ░
  ░      ░      ░      ░    ░         ░   ░ ░  ▒ ░   ░   ░ ░  ░ ░ ░    ░   ▒
         ░      ░  ░   ░  ░                 ░  ░           ░  ░   ░        ░  ░
                    ------------------------------------
                    || MeetNinja: The Google Meet Bot ||
                    ------------------------------------

Checking for MeetNinja updates... You are using the latest version!


Initializing browser...Traceback (most recent call last):
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 247, in <module>
    driver = initBrowser()
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 127, in initBrowser
    driver = webdriver.Chrome(service=serv, options=chromeOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 279, in <module>
    print(e)
NameError: name 'e' is not defined
```
And you won't have to respond every time, just a friendly reminder now and then.

**Comment by SHUR1K-N** [comment]
This is helpful information! I was under the impression this issue would be localized to Firefox, but this makes it a more generalized error, possibly independent of the browser.

I could not help but notice you have run MeetNinja.py using `python MeetNinja.py`, is your Python version 2.x.x or 3.x.x?

**Comment by denppa** [comment]
So My python version output of `python -V` is 3.9.1

This is what happens if I do it with `python3`
```
$  python3 MeetNinja.py 

   ███▄ ▄███▓▓█████ ▓█████▄▄▄█████▓ ███▄    █  ██▓ ███▄    █  ▄▄▄██▀▀▀▄▄▄
  ▓██▒▀█▀ ██▒▓█   ▀ ▓█   ▀▓  ██▒ ▓▒ ██ ▀█   █ ▓██▒ ██ ▀█   █    ▒██  ▒████▄
  ▓██    ▓██░▒███   ▒███  ▒ ▓██░ ▒░▓██  ▀█ ██▒▒██▒▓██  ▀█ ██▒   ░██  ▒██  ▀█▄
  ▒██    ▒██ ▒▓█  ▄ ▒▓█  ▄░ ▓██▓ ░ ▓██▒  ▐▌██▒░██░▓██▒  ▐▌██▒▓██▄██▓ ░██▄▄▄▄██
  ▒██▒   ░██▒░▒████▒░▒████▒ ▒██▒ ░ ▒██░   ▓██░░██░▒██░   ▓██░ ▓███▒   ▓█   ▓██▒
  ░ ▒░   ░  ░░░ ▒░ ░░░ ▒░ ░ ▒ ░░   ░ ▒░   ▒ ▒ ░▓  ░ ▒░   ▒ ▒  ▒▓▒▒░   ▒▒   ▓▒█░
  ░  ░      ░ ░ ░  ░ ░ ░  ░   ░    ░ ░░   ░ ▒░ ▒ ░░ ░░   ░ ▒░ ▒ ░▒░    ▒   ▒▒ ░
  ░      ░      ░      ░    ░         ░   ░ ░  ▒ ░   ░   ░ ░  ░ ░ ░    ░   ▒
         ░      ░  ░   ░  ░                 ░  ░           ░  ░   ░        ░  ░
                    ------------------------------------
                    || MeetNinja: The Google Meet Bot ||
                    ------------------------------------

Checking for MeetNinja updates... You are using the latest version!


Initializing browser...Traceback (most recent call last):
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 247, in <module>
    driver = initBrowser()
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 141, in initBrowser
    driver = webdriver.Firefox(service=serv, options=firefoxOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 279, in <module>
    print(e)
NameError: name 'e' is not defined
```

**Comment by SHUR1K-N** [comment]
Alright, I have a theory, and it comes from experiencing this before, but... Could you downgrade your Python version to 3.8.6 if possible and see if that helps? Many Python packages have yet to catch up and be 100% compatible with Python 3.9.0, and this might be the culprit. All of my Linux machines are on Python 3.8.6, and an update would break quite a lot of things on my end...

**Comment by SHUR1K-N** [comment]
Also, could you check if a "geckodriver.log" file has generated in the directory? If so, could you share its content here?

**Comment by denppa** [comment]
Okay, so I added the 3.8.7 python, and am reinstalling the whole thing from a git clone again. So sadly that file was removed, let me try to pip install it again, and then see what it can do.

Which version of selenium would you want me to install? That works best?

**Comment by denppa** [comment]
Any idea as to why this happened?
Am going to run the script again but in a virtual machine this time, which linux OS do you use?

```
$  python3.8 MeetNinja.py 
Traceback (most recent call last):
  File "MeetNinja.py", line 3, in <module>
    from selenium import webdriver; import requests
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 29, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 27, in <module>
    from .remote_connection import RemoteConnection
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 24, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```

**Comment by SHUR1K-N** [comment]
That's fine, the "geckodriver.log" file can be considered as secondary for the time being . I have never updated Selenium, just checked the version and it is 4.0.0a1. My Linux machines are running 64-bit Kali distributions; some physical, some virtual.

Your "urllib3" traceback is quite strange, this should not be happening. Anyway, try manually installing "urllib3" using `pip3 install urllib3`?

**Comment by denppa** [comment]
It is going to take some time for me to get the ubuntu up and running with python 3, I will let you know when I have it.

**Comment by SHUR1K-N** [comment]
Alright, awesome work, comrade! I'll be researching and testing different versions at my end as well and update here if I find something juicy.

**Comment by denppa** [comment]
Update!

So I was able to run the program with `python3.8` in my host machine, my VM is still setting up. This error still gets returned to me sadly. 

The drive log had absolutely nothing in it though.

Included is my changes to the code:
```
#!/usr/bin/env python

from selenium import webdriver; import requests
from selenium.webdriver.support import expected_conditions as when
from selenium.webdriver.common.by import By as by
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.service import Service
import pause; import os; import re
import time; from datetime import datetime
import colorama; from termcolor import colored

colorama.init()

###################################################################
#                        Meets                  HH:MM:SS DD/MM/YYYY
MEETS = {"1 https://meet.google.com/class-I'm-in": "10:20:00 2/2/2021",
         "2 https://meet.google.com/meetURL2": "23:59:59 31/12/2020",
         "3 https://meet.google.com/meetURL3": "23:59:59 31/12/2020",
         "4 https://meet.google.com/meetURL4": "23:59:59 31/12/2020",
         # Add more Meet URLs (if any) using the same format as above
         }

DURATION = 60 # Duration of each Meet in minutes
USERNAME = "myemail"
PASSWORD = "myPass"
BROWSER_DRIVER = "FirefoxDrivers/linux64/geckodriver"
```

```
$  python3 MeetNinja.py 

   ███▄ ▄███▓▓█████ ▓█████▄▄▄█████▓ ███▄    █  ██▓ ███▄    █  ▄▄▄██▀▀▀▄▄▄
  ▓██▒▀█▀ ██▒▓█   ▀ ▓█   ▀▓  ██▒ ▓▒ ██ ▀█   █ ▓██▒ ██ ▀█   █    ▒██  ▒████▄
  ▓██    ▓██░▒███   ▒███  ▒ ▓██░ ▒░▓██  ▀█ ██▒▒██▒▓██  ▀█ ██▒   ░██  ▒██  ▀█▄
  ▒██    ▒██ ▒▓█  ▄ ▒▓█  ▄░ ▓██▓ ░ ▓██▒  ▐▌██▒░██░▓██▒  ▐▌██▒▓██▄██▓ ░██▄▄▄▄██
  ▒██▒   ░██▒░▒████▒░▒████▒ ▒██▒ ░ ▒██░   ▓██░░██░▒██░   ▓██░ ▓███▒   ▓█   ▓██▒
  ░ ▒░   ░  ░░░ ▒░ ░░░ ▒░ ░ ▒ ░░   ░ ▒░   ▒ ▒ ░▓  ░ ▒░   ▒ ▒  ▒▓▒▒░   ▒▒   ▓▒█░
  ░  ░      ░ ░ ░  ░ ░ ░  ░   ░    ░ ░░   ░ ▒░ ▒ ░░ ░░   ░ ▒░ ▒ ░▒░    ▒   ▒▒ ░
  ░      ░      ░      ░    ░         ░   ░ ░  ▒ ░   ░   ░ ░  ░ ░ ░    ░   ▒
         ░      ░  ░   ░  ░                 ░  ░           ░  ░   ░        ░  ░
                    ------------------------------------
                    || MeetNinja: The Google Meet Bot ||
                    ------------------------------------

Checking for MeetNinja updates... You are using the latest version!


Initializing browser...Traceback (most recent call last):
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 247, in <module>
    driver = initBrowser()
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 141, in initBrowser
    driver = webdriver.Firefox(service=serv, options=firefoxOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 279, in <module>
    print(e)
NameError: name 'e' is not defined
```

**Comment by denppa** [comment]
Same problem in ubuntu with 3.8.6 python

```
$ python3 MeetNinja.py 

   ███▄ ▄███▓▓█████ ▓█████▄▄▄█████▓ ███▄    █  ██▓ ███▄    █  ▄▄▄██▀▀▀▄▄▄
  ▓██▒▀█▀ ██▒▓█   ▀ ▓█   ▀▓  ██▒ ▓▒ ██ ▀█   █ ▓██▒ ██ ▀█   █    ▒██  ▒████▄
  ▓██    ▓██░▒███   ▒███  ▒ ▓██░ ▒░▓██  ▀█ ██▒▒██▒▓██  ▀█ ██▒   ░██  ▒██  ▀█▄
  ▒██    ▒██ ▒▓█  ▄ ▒▓█  ▄░ ▓██▓ ░ ▓██▒  ▐▌██▒░██░▓██▒  ▐▌██▒▓██▄██▓ ░██▄▄▄▄██
  ▒██▒   ░██▒░▒████▒░▒████▒ ▒██▒ ░ ▒██░   ▓██░░██░▒██░   ▓██░ ▓███▒   ▓█   ▓██▒
  ░ ▒░   ░  ░░░ ▒░ ░░░ ▒░ ░ ▒ ░░   ░ ▒░   ▒ ▒ ░▓  ░ ▒░   ▒ ▒  ▒▓▒▒░   ▒▒   ▓▒█░
  ░  ░      ░ ░ ░  ░ ░ ░  ░   ░    ░ ░░   ░ ▒░ ▒ ░░ ░░   ░ ▒░ ▒ ░▒░    ▒   ▒▒ ░
  ░      ░      ░      ░    ░         ░   ░ ░  ▒ ░   ░   ░ ░  ░ ░ ░    ░   ▒
         ░      ░  ░   ░  ░                 ░  ░           ░  ░   ░        ░  ░
                    ------------------------------------
                    || MeetNinja: The Google Meet Bot ||
                    ------------------------------------

Checking for MeetNinja updates... You are using the latest version!


Initializing browser...Traceback (most recent call last):
  File "MeetNinja.py", line 247, in <module>
    driver = initBrowser()
  File "MeetNinja.py", line 141, in initBrowser
    driver = webdriver.Firefox(service=serv, options=firefoxOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MeetNinja.py", line 279, in <module>
    print(e)
NameError: name 'e' is not defined
```

**Comment by SHUR1K-N** [comment]
What a pain in the posterior! Alright, well, you may use MeetNinja in the meantime with the following workaround:-

In MeetNinja.py, from [line #137](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/blob/4b700045a97e7862863e90e4163ac99f0cd59234/MeetNinja.py#L137):
```
if BROWSER_DRIVER.lower().endswith(".exe"):
        driver = webdriver.Firefox(executable_path=BROWSER_DRIVER, options=firefoxOptions)
else:
        serv = Service(BROWSER_DRIVER)
        driver = webdriver.Firefox(service=serv, options=firefoxOptions)
```
You may reduce this entire section down to just:
`driver = webdriver.Firefox(executable_path=BROWSER_DRIVER, options=firefoxOptions)`

Making this change, MeetNinja will show you a deprecation warning and encourage you to use "service" (I know, right?!), but will operate just fine after that; so you may ignore that warning.

**Comment by denppa** [comment]
Damn, for me it popped up one more error now:
(Sorry you have to to through this... Really appreciate the help though)
```
$  python3 MeetNinja.py 

   ███▄ ▄███▓▓█████ ▓█████▄▄▄█████▓ ███▄    █  ██▓ ███▄    █  ▄▄▄██▀▀▀▄▄▄
  ▓██▒▀█▀ ██▒▓█   ▀ ▓█   ▀▓  ██▒ ▓▒ ██ ▀█   █ ▓██▒ ██ ▀█   █    ▒██  ▒████▄
  ▓██    ▓██░▒███   ▒███  ▒ ▓██░ ▒░▓██  ▀█ ██▒▒██▒▓██  ▀█ ██▒   ░██  ▒██  ▀█▄
  ▒██    ▒██ ▒▓█  ▄ ▒▓█  ▄░ ▓██▓ ░ ▓██▒  ▐▌██▒░██░▓██▒  ▐▌██▒▓██▄██▓ ░██▄▄▄▄██
  ▒██▒   ░██▒░▒████▒░▒████▒ ▒██▒ ░ ▒██░   ▓██░░██░▒██░   ▓██░ ▓███▒   ▓█   ▓██▒
  ░ ▒░   ░  ░░░ ▒░ ░░░ ▒░ ░ ▒ ░░   ░ ▒░   ▒ ▒ ░▓  ░ ▒░   ▒ ▒  ▒▓▒▒░   ▒▒   ▓▒█░
  ░  ░      ░ ░ ░  ░ ░ ░  ░   ░    ░ ░░   ░ ▒░ ▒ ░░ ░░   ░ ▒░ ▒ ░▒░    ▒   ▒▒ ░
  ░      ░      ░      ░    ░         ░   ░ ░  ▒ ░   ░   ░ ░  ░ ░ ░    ░   ▒
         ░      ░  ░   ░  ░                 ░  ░           ░  ░   ░        ░  ░
                    ------------------------------------
                    || MeetNinja: The Google Meet Bot ||
                    ------------------------------------

Checking for MeetNinja updates... You are using the latest version!


Initializing browser...Traceback (most recent call last):
  File "/home/asmodean/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'FirefoxDrivers/linux64/geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asmodean/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 248, in <module>
    driver = initBrowser()
  File "/home/asmodean/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 137, in initBrowser
    driver = webdriver.Firefox(executable_path=BROWSER_DRIVER, options=firefoxOptions)
  File "/home/asmodean/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/asmodean/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable may have wrong permissions. 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asmodean/git/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 280, in <module>
    print(e)
NameError: name 'e' is not defined```

**Comment by SHUR1K-N** [comment]
Hey, no worries!

This should be an easy one, you just have not given the correct permissions (or *any* permissions, in fact) to the files that came with MeetNinja. Just open a terminal window inside the MeetNinja directory and execute the following:

`chmod 777 ./ -R`

This will give read, write, and execute permissions for all subdirectories under MeetNinja's main directory recursively.

**Comment by denppa** [comment]
Okay, I just changed the permissions of the gecko driver and the Browser finally launched!

**Comment by SHUR1K-N** [comment]
Awesome! This is how MeetNinja operated before, but I did not like the deprecation warning spoiling the beautiful (subjective) colorful verbose messages, so used "Service" as suggested by that very deprecation warning. Sadly, that very change seems to cause inconsistency and mystery.

I think I will just change it back to the version which displays the deprecation warning. At least MeetNinja would work for people who need it immediately!

**Comment by denppa** [comment]
Okay, I think we can close the issue. I did not get the warning by the way. So I suppose it is not there on Arch?

**Comment by denppa** [comment]
Would you mind to send me your discord somehow? I would want to discuss somethings with you in private.

**Comment by denppa** [comment]
Yup, no errors:
```$  python MeetNinja.py 

   ███▄ ▄███▓▓█████ ▓█████▄▄▄█████▓ ███▄    █  ██▓ ███▄    █  ▄▄▄██▀▀▀▄▄▄
  ▓██▒▀█▀ ██▒▓█   ▀ ▓█   ▀▓  ██▒ ▓▒ ██ ▀█   █ ▓██▒ ██ ▀█   █    ▒██  ▒████▄
  ▓██    ▓██░▒███   ▒███  ▒ ▓██░ ▒░▓██  ▀█ ██▒▒██▒▓██  ▀█ ██▒   ░██  ▒██  ▀█▄
  ▒██    ▒██ ▒▓█  ▄ ▒▓█  ▄░ ▓██▓ ░ ▓██▒  ▐▌██▒░██░▓██▒  ▐▌██▒▓██▄██▓ ░██▄▄▄▄██
  ▒██▒   ░██▒░▒████▒░▒████▒ ▒██▒ ░ ▒██░   ▓██░░██░▒██░   ▓██░ ▓███▒   ▓█   ▓██▒
  ░ ▒░   ░  ░░░ ▒░ ░░░ ▒░ ░ ▒ ░░   ░ ▒░   ▒ ▒ ░▓  ░ ▒░   ▒ ▒  ▒▓▒▒░   ▒▒   ▓▒█░
  ░  ░      ░ ░ ░  ░ ░ ░  ░   ░    ░ ░░   ░ ▒░ ▒ ░░ ░░   ░ ▒░ ▒ ░▒░    ▒   ▒▒ ░
  ░      ░      ░      ░    ░         ░   ░ ░  ▒ ░   ░   ░ ░  ░ ░ ░    ░   ▒
         ░      ░  ░   ░  ░                 ░  ░           ░  ░   ░        ░  ░
                    ------------------------------------
                    || MeetNinja: The Google Meet Bot ||
                    ------------------------------------

Checking for MeetNinja updates... You are using the latest version!


Initializing browser... Success!
Waiting until first Meet start time [11:10:00 2/2/2021]... Started!
```

**Comment by SHUR1K-N** [comment]
Strange! I will test some stuff and push out an update within 1-2 hours that fixes this whole thing, hopefully. Glad it works for you!

**Comment by SHUR1K-N** [comment]
Regarding Discord, you may message me @SHUR1KEN#3819. As soon as you do, I will delete this message here.

**Comment by ch92787830** [comment]
Friend Request is sent.

**Comment by denppa** [comment]
If you let people know, to give the files in the directory this permission:
```
chmod 744 -R path-to-git-clone-folder-of-meetninja
```
It would work fine!

**Comment by SHUR1K-N** [comment]
it's in one of the very recent comments above already.
